name: "Create/Update tag"
description: "Creates or updates a tag for a given commit."
author: "Sangeeta"
inputs:
  github_token:
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    default: "${{ github.token }}"
  tag:
    description: "Tag you want to create or update."
    required: true
  message:
    description: "Tag message."
    required: false
  tag_exists_error:
    description: "Optional. Whether to throw an error when the tag already exists. Defaults to 'true'."
    required: false
    default: "true"
  no_verify_tag:
    description: "Optional. Skips verifying when pushing the tag. Defaults to 'false'."
    required: false
    default: "false"
outputs:
  tag_exists:
    description: "Whether the tag already existed."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@main
branding:
  icon: "tag"
  color: "blue"
